name: "Quori ROS CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Install LLVM
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo ln -s /usr/lib/llvm-11/lib/libclang.so.1 /usr/lib/llvm-11/lib/libclang.so
      - uses: actions/checkout@v2
        with:
          path: quori_ros
      - uses: actions/checkout@v2
        with:
          path: drydoc
          repository: semio-ai/drydoc
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build
        env:
          LLVM_CONFIG_PATH: /usr/bin/llvm-config-11
          LIBCLANG_PATH: /usr/lib/llvm-11/lib
        working-directory: drydoc
      - run: drydoc gen
        working-directory: quori_ros
        env:
          PATH: $GITHUB_WORKSPACE/drydoc/target/debug
      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: DEPLOY_KEY
          publish_dir: html
