name: "Quori ROS CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - run: sudo apt-get install wget
      - run: wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.1/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
        working-directory: $GITHUB_WORKSPACE
      - run: ls =a
      - run: tar -xvf clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
        working-directory: $GITHUB_WORKSPACE
      - run: ls -a llvm
      - uses: actions/checkout@v2
        with:
          path: quori_ros
      - uses: actions/checkout@v2
        with:
          path: drydoc
          repository: semio-ai/drydoc
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build
        working-directory: drydoc
        env:
          LLVM_PATH: $GITHUB_WORKSPACE/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-16.04/
      - run: drydoc gen
        working-directory: quori_ros
        env:
          PATH: $GITHUB_WORKSPACE/drydoc/target/debug
      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: DEPLOY_KEY
          publish_dir: html
